### PR TITLE
Allow for passing list of error and help messages

### PR DESCRIPTION
**Pull request by Zeragamba**
Allows users to override the default messages for things like unknown command, further help, etc...

I made these change really quickly before bed, but wanted to get a ball rolling for this. I haven't run any of the tests, which i can do later in the week.

### CODE REVIEW

**Comment by MeLlamoPablo** [comment]
Looks good, thanks for the contribution!

I've pushed a commit to your repo, review it, and if you agree with it this should be ready to merge.

**Comment by Zeragamba** [comment]
Looks good to me

**Comment by MeLlamoPablo** [comment]
Good. I want to make some small changes to the docs later today if I can. After that I'll publish the new version to npm.

**Comment by Zeragamba** [comment]
Awesome, later i may take a larger look at this to see if there's stuff that could be added for a version 1.4.

Thanks. For now, i'm off to go make a pull request into generator-discordbot

**Pull request merged**
